spring:
  application:
    name: razorpay

  datasource:
    # Database connection properties it will check in environment variables first and if not found it will use the default values provided after the colon
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpayDB}
    # this will also work the same ways as above
    #url: jdbc:postgresql://localhost:5432/razorpayDB
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

  JPA:
    #this will automatically create the tables in the database if they don't exist and update them if they do exist
    hibernate:
      ddl-auto: update

    #this will show the sql queries in the console
    show-sql: true

    #this will format the sql queries in the console
    properties:
      hibernate:
        format_sql: true
        #this will set the dialect for the database, in this case it is set to PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
#debug: true